### ISSUE TITLE
freeze when X tries to start

### ISSUE THREAD

**Issue by the-unusual** [gohai/vc4-buildbot#2]
After the kernel and everything else was compiled (using config tweaks from #1), when I rebooted the Pi, it froze when X attempted to start.

**Comment by CalcProgrammer1** [comment]
Yeah, it did that for me too.  I don't remember the exact error.  I built my Mesa differently - got the source from "apt-get source mesa" and added vc4 to the --with-gallium-drivers in debian/rules.  X started, the Xorg log showed vc4 for DRI2, but the screen went blank and an error showed up in dmesg.

I'm going to repeat with Pi 2 and Debian Sid (instead of Raspbian) and see if I can get that working.

**Comment by the-unusual** [comment]
I was able to fix it by making a symlink from /usr/bin/X to /usr/local/bin/X. When I ran X, it started fine, but when I tried startx it gave me a corrupted login screen before it segfaulted. I have figured out that this is also the case for when LightDM is running.

**Comment by gohai** [comment]
@HoboHacker @CalcProgrammer1 

Yes, so far I've also only seen the corrupted screen, and it does sometimes lock up on the Pi 2 when using upstream-based kernels. This is all very much in flux still, but I expect it to work very soon.

With regards to building: this is specifically made for being run on Raspbian.
